### PR TITLE
Change type of obstacle message callback

### PR DESCRIPTION
**Pull request by timonegk**
## Proposed changes
Related to #125. This change is not a solution but changes the subscription to avoid the message type conflict.

### CODE REVIEW

**Review by texhnolyze — APPROVED** [review]
Works for a quick fix :+1: 
Further work will be done in https://github.com/bit-bots/humanoid_league_misc/pull/127

**Comment by timonegk** [comment]
Regarding future work, I talked to @Flova and he said that the vision already uses the robot messages and never publishes obstacle messages, so we only need to change it here and can drop the obstacles.

**Comment by jaagut** [comment]
What's the status of this PR? Do we want/need to continue with it?

**Comment by Flova** [comment]
I think it has been superseded by #127

**Pull request closed without merging**
