### PR TITLE
Project masks in the transformer

### LINKED ISSUE #38: Transformer: Transform image mask to point cloud
## Is your feature request related to a problem? Please describe.
Currently, only line points can be transformed. But line points generate additional overhead in the vision and carry less information than a line mask image. Also the line points message is not optimal.

## Describe the solution you'd like
I suggest, supporting the transform of mask images into point cloud to reduce the overhead and provide more line information for the localization.

## Describe alternatives you've considered
Alternatively, the image mask could be transformed into a perspectively warped image, but this is harder for the localization to use.

### PR DESCRIPTION
**Pull request by Flova**
## Proposed changes
- Project image masks as point clouds onto the field plane
- Optimize the transformer speed using NumPy optimizations

## Related issues
Closes #38

### CODE REVIEW

**Comment by Flova** [comment]
I would use the array transform methods at other places too later on.

**Comment by Flova** [comment]
I tried to test the whole thing in simulation but it seemed quite hard. Therefore I have a look at it next time in the Lab.

**Comment by Flova** [comment]
Ping @timonegk 
I would go to the lab in the next few days. It would be cool if some changes are requested before the whole thing gets tested on the robot.

**Review by timonegk — APPROVED** [review]
Sorry for the delay. The changes look good to me, but I was unfortunately unable to test them.

**Pull request merged**
